# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Minecraft | 九音
subtitle: A Minecraft Player & Modder
description: A Minecraft Player & Modder
keywords: RADITECH
author: RyTinSelver
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://mc.rytinselver.com/
root: /
permalink: categories/:category/:abbrlink.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: post
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: NexT

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: cos
  appId: 1258502213
  secretId: AKIDSggUAE2HDoWdk3qnSVZR7aaPq3pKsniN
  secretKey: aua3vnDem1A9t680l8IkzA8jLkCPYQCj
  bucket: mc-rytinselver-1258502213
  region: ap-shanghai

# Hexo-generator-search
search:
  path: search.xml
  field: post
  format: html

# Sitemap
baidusitemap:
  path: baidusitemap.xml
sitemap:
  path: sitemap.xml

# Security
encrypt:
  enable: true

# Backup
backup:
  type: git
  theme: NexT
  message: hexo mc backup
  repository:
    github: git@github.com:RyTinSelver/RyTinSelver-backup.git,mc
